apiVersion: v1
kind: Service
metadata:
  labels:
    name: semapi
  name: semapi
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    name: semapi
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semapi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: semapi
  template:
    metadata:
      labels:
        name: semapi
    spec:
      containers:
        - image: tcia/prism_semapi:latest
          env:
            - name: SEMAPI_TRIPLESTORE_URL
              value: "http://triplestore:7200/repositories/prism"
          imagePullPolicy: Always
          name: semapi
          ports:
            - containerPort: 3000
      restartPolicy: Always

