apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: back
  name: ca-security
spec:
  ports:
  - name: "4010"
    port: 4010
    targetPort: 4010
  selector:
    name: back
status:
  loadBalancer: {}
