apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: heatmaploader
    prism: heatmaploader
    pathdb: heatmaploader
  name: heatmaploader
spec:
  replicas: 1
  selector:
    matchLabels:
      name: heatmaploader
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: heatmaploader
        prism: heatmaploader
        pathdb: heatmaploader
    spec:
      containers:
      - env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
        - name: TZ
          value: America/New_York
        image: camicroscope/pathdb-heatmaploader:latest
        imagePullPolicy: ""
        name: quip-hmloader
        resources: {}
        volumeMounts:
        - mountPath: /mnt/data/
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
