apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: iip
  name: iip
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iip
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: iip
    spec:
      containers:
      - image: camicroscope/iipimage:latest
        imagePullPolicy: Always
        name: ca-iip
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /data/images
          name: data
          subPath: 'pathdb/files/wsi'
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
