apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: iip
    prism: ca-iip
    pathdb: ca-iip
  name: ca-iip
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 8443
  selector:
    name: iip
status:
  loadBalancer: {}
