apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: imageloader
    prism: imageloader
    pathdb: imageloader
  name: imageloader
spec:
  replicas: 1
  selector:
    matchLabels:
      name: imageloader
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: imageloader
        prism: imageloader
        pathdb: imageloader
    spec:
      containers:
      - image: jrutecht/imageloader:latest
        imagePullPolicy: ""
        name: quip-imageloader
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources: {}
        volumeMounts:
        - mountPath: /data/images
          name: data
          subPath: 'pathdb/files/wsi'
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
