apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: ca-mongo
  name: ca-mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: ca-mongo
status:
  loadBalancer: {}
