apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: quip-pathdb
    prism: quip-pathdb
    pathdb: quip-pathdb
  name: quip-pathdb
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 8443
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    name: pathdb
status:
  loadBalancer: {}
