apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: pathdb
    prism: pathdb
    pathdb: pathdb
  name: pathdb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pathdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: pathdb
        prism: pathdb
        pathdb: pathdb
    spec:
      containers:
      - args:
        - /config/pathdb_pre.sh
        image: jrutecht/pathdb:latest
        imagePullPolicy: ""
        name: quip-pathdb
        ports:
        - containerPort: 8443
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data/
          name: data
        - mountPath: /config/map
          name: httpd-conf
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: httpd-conf
        configMap:
          name: httpd-conf
status: {}
