apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: segloader
    prism: segloader
    pathdb: segloader
  name: segloader
spec:
  replicas: 1
  selector:
    matchLabels:
      name: segloader
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: segloader
        prism: segloader
        pathdb: segloader
    spec:
      containers:
      - image: jrutecht/segloader:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        imagePullPolicy: ""
        name: quip-segloader
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
