apiVersion: v1
kind: Service
metadata:
  labels:
    name: coreapi
  name: coreapi
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    name: coreapi
status:
  loadBalancer: {}
