apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"core","namespace":"prism-core"},"spec":{"selector":{"matchLabels":{"app":"core"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"core"}},"spec":{"containers":[{"env":[{"name":"API_WORKERS","value":"4"},{"name":"API_PORT","value":"8000"},{"name":"MONGO_USER","valueFrom":{"secretKeyRef":{"key":"database-user","name":"mongodb"}}},{"name":"MONGO_PASS","valueFrom":{"secretKeyRef":{"key":"database-password","name":"mongodb"}}},{"name":"MONGO_DATABASE","valueFrom":{"secretKeyRef":{"key":"database-name","name":"mongodb"}}}],"image":"tcia/prism-core:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/v1/other/test","port":8000},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"name":"core","ports":[{"containerPort":8000,"name":"core"}],"readinessProbe":{"httpGet":{"path":"/v1/other/test","port":8000},"initialDelaySeconds":5,"periodSeconds":2,"timeoutSeconds":1},"volumeMounts":[{"mountPath":"/storage","name":"core-persistent-storage"}]}],"volumes":[{"name":"core-persistent-storage","persistentVolumeClaim":{"claimName":"core-pv-claim-auto"}}]}}}}
  creationTimestamp: 2020-11-30T17:55:31Z
  generation: 5
  labels:
    app: core
    date: "1606930661"
  name: core
  namespace: prism-core
  resourceVersion: "120423037"
  selfLink: /apis/extensions/v1beta1/namespaces/prism-core/deployments/core
  uid: 3d3475f4-3335-11eb-9cb3-0050569f5fc8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: core
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: core
        date: "1606931428"
    spec:
      containers:
      - env:
        - name: API_WORKERS
          value: "4"
        - name: API_PORT
          value: "8000"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mongodb
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongodb
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mongodb
        image: tcia/prism-core:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/other/test
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: core
        ports:
        - containerPort: 8000
          name: core
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/other/test
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /storage
          name: core-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: core-persistent-storage
        persistentVolumeClaim:
          claimName: core-pv-claim-auto
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-11-30T17:55:31Z
    lastUpdateTime: 2020-12-02T17:51:12Z
    message: ReplicaSet "core-5dd594856c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2022-02-02T21:18:22Z
    lastUpdateTime: 2022-02-02T21:18:22Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
