apiVersion: v1
kind: Secret
metadata:
    name: mongodb
type: Opaque
stringData:
    database-name: **********
    database-user: prismmongouser
    database-password: **********
    database-admin-password: **********
