kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-api-configmap
data:
  api.conf: |
      server {
          listen 8080;

          location / {
              try_files $uri $uri/ /index.html;
              add_header   Cache-Control public;
              expires      1d;
              root   /app;
          }

          location /api {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://api:8080/v1;
          }

          location /coreapi {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://coreapi:8000/v1;
          }

          location /semapi {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://sui-demo-prism.apps.dbmi.cloud/api;
          }
      }